In [1]:
import os
import re
import cv2
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score, precision_score, recall_score, roc_auc_score
from tensorflow.keras.models import load_model

In [ ]:
project_dir = os.path.join(os.getcwd(), "Project1")
model = load_model("model3_2.h5")
T_m = 0.4
T_b = 0.4
target_size = (224, 224)
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}


In [3]:

X_test = np.load("X_test_2_3.npy")
y_test = np.load("y_test_2_3.npy")

In [4]:
probs = model.predict(X_test)
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]

In [5]:
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")

              precision    recall  f1-score   support

      normal       0.99      0.97      0.98       187
      benign       0.71      0.95      0.81        39
      cancer       1.00      0.25      0.40        12

    accuracy                           0.93       238
   macro avg       0.90      0.72      0.73       238
weighted avg       0.94      0.93      0.92       238

Confusion Matrix:
 [[181   6   0]
 [  2  37   0]
 [  0   9   3]]
Accuracy: 0.9285714285714286
Precision: 0.9002031665966093
Recall: 0.7222107957402075
📌 F1 Score: 0.7305217305217305
AUC: 0.9566798038207818
