In [1]:
import os
import re
import cv2
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score, precision_score, recall_score, roc_auc_score
from tensorflow.keras.models import load_model

In [2]:
project_dir = os.path.join(os.getcwd(), "Project1")
model = load_model("model1_2.h5")
T_m = 0.4
T_b = 0.4
target_size = (224, 224)
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}
pattern = re.compile(r'^[A-Z]_\d+_\d+\.(LEFT|RIGHT)_(CC|MLO)\.jpg$', re.IGNORECASE)

In [3]:

X_test = np.load("X_test_2_1.npy")
y_test = np.load("y_test_2_1.npy")

In [4]:
probs = model.predict(X_test)
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]

In [5]:
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")

              precision    recall  f1-score   support

      normal       0.98      0.97      0.97       187
      benign       0.71      0.92      0.80        39
      cancer       1.00      0.17      0.29        12

    accuracy                           0.92       238
   macro avg       0.89      0.69      0.69       238
weighted avg       0.93      0.92      0.91       238

Confusion Matrix:
 [[181   6   0]
 [  3  36   0]
 [  1   9   2]]
Accuracy: 0.9201680672268907
Precision: 0.8947535771065183
Recall: 0.6858860094154212
📌 F1 Score: 0.6862775217613928
AUC: 0.9487354324349341
