#### 📌 **HİPERPARAMETRELERİ BURADAN AYARLA**

In [1]:
import os
import re
import cv2
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score, precision_score, recall_score, roc_auc_score
from tensorflow.keras.models import load_model

In [2]:
project_dir = os.path.join(os.getcwd(), "Project1")
model = load_model("model1.h5")
T_m = 0.51
T_b = 0.4
target_size = (224, 224)
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}
pattern = re.compile(r'^[A-Z]_\d+_\d+\.(LEFT|RIGHT)_(CC|MLO)\.jpg$', re.IGNORECASE)

In [3]:

X_test = np.load("X_test_1_1.npy")
y_test = np.load("y_test_1_1.npy")

In [4]:
probs = model.predict(X_test)
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]

 Metirkler**

In [5]:
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")

              precision    recall  f1-score   support

      normal       0.75      0.85      0.79       241
      benign       0.55      0.57      0.56       268
      cancer       0.64      0.54      0.58       272

    accuracy                           0.65       781
   macro avg       0.65      0.65      0.65       781
weighted avg       0.64      0.65      0.64       781

Confusion Matrix:
 [[205  33   3]
 [ 35 153  80]
 [ 35  91 146]]
Accuracy: 0.645326504481434
Precision: 0.6451185670014986
Recall: 0.6527608783031389
📌 F1 Score: 0.6462919548854783
AUC: 0.8349347011711998
