In [15]:
import os
import re
import cv2
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score, precision_score, recall_score, roc_auc_score
from tensorflow.keras.models import load_model

In [16]:
project_dir = os.path.join(os.getcwd(), "Project1")
model = load_model("model2.h5")
T_m = 0.46
T_b = 0.4
target_size = (224, 224)
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}
pattern = re.compile(r'^[A-Z]_\d+_\d+\.(LEFT|RIGHT)_(CC|MLO)\.jpg$', re.IGNORECASE)

In [17]:


X_test = np.load("X_test_1_2.npy")
y_test = np.load("y_test_1_2.npy")

In [18]:
probs = model.predict(X_test)
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]

In [19]:
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")

              precision    recall  f1-score   support

      normal       0.83      0.84      0.84       241
      benign       0.64      0.70      0.67       268
      cancer       0.72      0.64      0.68       272

    accuracy                           0.72       781
   macro avg       0.73      0.73      0.73       781
weighted avg       0.73      0.72      0.72       781

Confusion Matrix:
 [[202  31   8]
 [ 20 188  60]
 [ 20  77 175]]
Accuracy: 0.7234314980793854
Precision: 0.730003495996762
Recall: 0.7276830547045102
📌 F1 Score: 0.7275724135158496
AUC: 0.8864164554366522
