In [1]:
import os
import re
import cv2
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score, precision_score, recall_score, roc_auc_score
from tensorflow.keras.models import load_model
import joblib
import xgboost as xgb


**#### 🧠 **MLP****

In [2]:
model = load_model("MLP_1_2.h5")
T_m = 0.40
T_b = 0.40
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}


In [3]:


X_test = np.load("X_test_2_1.npy")
y_test = np.load("y_test_2_1.npy")

In [4]:
probs = model.predict(X_test)
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]

 Metirkler**

In [5]:
print("\n --------------MLP RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------MLP RESULTS----------------
              precision    recall  f1-score   support

      normal       0.79      1.00      0.88       187
      benign       0.00      0.00      0.00        39
      cancer       0.00      0.00      0.00        12

    accuracy                           0.79       238
   macro avg       0.26      0.33      0.29       238
weighted avg       0.62      0.79      0.69       238

Confusion Matrix:
 [[187   0   0]
 [ 39   0   0]
 [ 12   0   0]]
Accuracy: 0.7857142857142857
Precision: 0.2619047619047619
Recall: 0.3333333333333333
📌 F1 Score: 0.29333333333333333
AUC: 0.5827454185742762


c:\Users\Dr.Ahmet\anaconda3\envs\tf-gpu-211\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Dr.Ahmet\anaconda3\envs\tf-gpu-211\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Dr.Ahmet\anaconda3\envs\tf-gpu-211\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

**#### 🧠 **RANDOM FOREST****

In [6]:
model = joblib.load("RF_2_1.pkl")
T_m = 0.55
T_b = 0.40
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}

In [7]:
X_test = np.load("X_test_2_1.npy")
y_test = np.load("y_test_2_1.npy")
probs = model.predict_proba(X_test) 
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]
print("\n --------------RF RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------RF RESULTS----------------
              precision    recall  f1-score   support

      normal       0.81      0.91      0.86       187
      benign       0.33      0.23      0.27        39
      cancer       0.00      0.00      0.00        12

    accuracy                           0.76       238
   macro avg       0.38      0.38      0.38       238
weighted avg       0.69      0.76      0.72       238

Confusion Matrix:
 [[171  16   0]
 [ 30   9   0]
 [ 10   2   0]]
Accuracy: 0.7563025210084033
Precision: 0.38125329120589785
Recall: 0.38173591114767585
📌 F1 Score: 0.3773412517131111
AUC: 0.6255389205703309


c:\Users\Dr.Ahmet\anaconda3\envs\tf-gpu-211\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Dr.Ahmet\anaconda3\envs\tf-gpu-211\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Dr.Ahmet\anaconda3\envs\tf-gpu-211\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

**#### 🧠 **XP-Boost****

In [8]:
loaded_xgb_model_booster = xgb.Booster() # Initialize an empty booster
loaded_xgb_model_booster.load_model("XGBoost_2_1.json") # Load the model into the booster object
# No need for 'model =' here, loaded_xgb_model_booster now holds the model
T_m = 0.40
T_b = 0.55
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}

X_test = np.load("X_test_2_1.npy")
y_test = np.load("y_test_2_1.npy")

dtest_predict = xgb.DMatrix(X_test) 
probs = loaded_xgb_model_booster.predict(dtest_predict) 
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]



In [9]:

print("\n --------------XP-B RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------XP-B RESULTS----------------
              precision    recall  f1-score   support

      normal       0.80      0.98      0.88       187
      benign       0.62      0.13      0.21        39
      cancer       1.00      0.08      0.15        12

    accuracy                           0.80       238
   macro avg       0.81      0.40      0.42       238
weighted avg       0.78      0.80      0.74       238

Confusion Matrix:
 [[184   3   0]
 [ 34   5   0]
 [ 11   0   1]]
Accuracy: 0.7983193277310925
Precision: 0.8094978165938865
Recall: 0.3984985602632661
📌 F1 Score: 0.417075831969449
AUC: 0.5914411479726379
