In [1]:
import os
import re
import cv2
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score, precision_score, recall_score, roc_auc_score
from tensorflow.keras.models import load_model
import joblib
import xgboost as xgb


**#### 🧠 **MLP****

In [2]:
model = load_model("MLP_1_3.h5")
T_m = 0.22
T_b = 0.64
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}


In [3]:


X_test = np.load("X_test_1_3.npy")
y_test = np.load("y_test_1_3.npy")

In [4]:
probs = model.predict(X_test)
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]

 Metirkler**

In [5]:
print("\n --------------MLP RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------MLP RESULTS----------------
              precision    recall  f1-score   support

      normal       0.42      0.53      0.47       241
      benign       0.39      0.68      0.49       268
      cancer       0.38      0.01      0.02       272

    accuracy                           0.40       781
   macro avg       0.39      0.41      0.33       781
weighted avg       0.39      0.40      0.32       781

Confusion Matrix:
 [[128 110   3]
 [ 84 182   2]
 [ 92 177   3]]
Accuracy: 0.4007682458386684
Precision: 0.39470411102382824
Recall: 0.40708474044228454
📌 F1 Score: 0.3283491692022433
AUC: 0.5617580251800322


**#### 🧠 **RANDOM FOREST****

In [6]:
model = joblib.load("RF_1_3.pkl")
T_m = 0.46
T_b = 0.43
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}

In [7]:
X_test = np.load("X_test_1_3.npy")
y_test = np.load("y_test_1_3.npy")
probs = model.predict_proba(X_test) 
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]
print("\n --------------RF RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------RF RESULTS----------------
              precision    recall  f1-score   support

      normal       0.38      0.51      0.44       241
      benign       0.39      0.33      0.36       268
      cancer       0.38      0.32      0.35       272

    accuracy                           0.38       781
   macro avg       0.38      0.39      0.38       781
weighted avg       0.38      0.38      0.38       781

Confusion Matrix:
 [[124  51  66]
 [101  89  78]
 [ 98  87  87]]
Accuracy: 0.38412291933418696
Precision: 0.38419826333248136
Recall: 0.3888217716640134
📌 F1 Score: 0.3817455749776717
AUC: 0.5425813590844639


**#### 🧠 **XP-Boost****

In [8]:
loaded_xgb_model_booster = xgb.Booster() # Initialize an empty booster
loaded_xgb_model_booster.load_model("XGBoost_1_3.json") # Load the model into the booster object
# No need for 'model =' here, loaded_xgb_model_booster now holds the model
T_m = 0.37
T_b = 0.37
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}

X_test = np.load("X_test_1_3.npy")
y_test = np.load("y_test_1_3.npy")

dtest_predict = xgb.DMatrix(X_test) 
probs = loaded_xgb_model_booster.predict(dtest_predict) 
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]



In [9]:

print("\n --------------XP-B RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------XP-B RESULTS----------------
              precision    recall  f1-score   support

      normal       0.39      0.44      0.42       241
      benign       0.39      0.29      0.33       268
      cancer       0.38      0.44      0.41       272

    accuracy                           0.39       781
   macro avg       0.39      0.39      0.39       781
weighted avg       0.39      0.39      0.38       781

Confusion Matrix:
 [[107  50  84]
 [ 82  77 109]
 [ 83  70 119]]
Accuracy: 0.3879641485275288
Precision: 0.3885518511712898
Recall: 0.3895989451084825
📌 F1 Score: 0.3852903461252106
AUC: 0.5699903599561056
