#### 📌 **HİPERPARAMETRELERİ BURADAN AYARLA**

In [1]:
learning_rate = 1e-4
dropout_rate = 0.588
batch_size = 32
filters = [32, 64, 256]
earlystop_patience = 10
reduce_lr_patience = 5
epochs = 50
target_size = (224, 224)

In [2]:
import os
import re
import cv2
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import (classification_report, confusion_matrix, f1_score,
                             accuracy_score, roc_auc_score, precision_score, recall_score)
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (Input, Conv2D, BatchNormalization, ReLU,
                                     MaxPooling2D, Dropout, Flatten, Dense)
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

#### 📁 **1. Görüntü Yolu Listeleme Fonksiyonu**


In [ ]:
#chatgpt
def mammo_gorunumlerini_listele(kok_dizin):
    class_dirs = {
        'normal': ['Birad1'],
        'benign': ['Birad3'],
        'cancer': ['Birad4', 'Birad5'],
    }
    paths, labels = [], []
    for cls, subdirs in class_dirs.items():
        for sd in subdirs:
            dir_path = os.path.join(kok_dizin, sd)
            if not os.path.isdir(dir_path):
                continue
            for fname in sorted(os.listdir(dir_path)):
                if fname.lower().endswith(('.jpg', '.jpeg', '.png')):
                    paths.append(os.path.join(dir_path, fname))
                    labels.append(cls)
    return paths, labels

#### 🧼 **2. Görüntü Ön İşleme**


In [ ]:
#chatgpt ile ayırdım
def read_grayscale_image(path, target_size=target_size):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    img = cv2.resize(img, target_size)
    return img.astype(np.float32)

def normalize_image(img, method='minmax'):
    if method == 'minmax':
        return img / 255.0
    else:
        return (img - img.mean()) / (img.std() + 1e-8)

def convert_to_dataset(paths, labels, target_size=target_size, method='minmax'):
    X, y = [], []
    label_map = {'normal': 0, 'benign': 1, 'cancer': 2}
    for p, lbl in zip(paths, labels):
        img = read_grayscale_image(p, target_size)
        img = normalize_image(img, method)
        X.append(img[..., np.newaxis])
        y.append(label_map[lbl])
    return np.array(X), np.array(y)

#### 🧠 **3. CNN Model Tanımı**

In [5]:
def _conv_block(inputs, filters):
    x = Conv2D(filters, (6, 6), padding='same')(inputs)
    x = BatchNormalization()(x)
    x = ReLU()(x)
    return x
def create_cnn_model(input_shape=(224, 224, 1), num_classes=3, filters=filters, dropout_rate=dropout_rate):
    inp = Input(shape=input_shape)
    x = _conv_block(inp, filters[0])
    x = MaxPooling2D((2, 2))(x)

    x = _conv_block(x, filters[1])
    x = _conv_block(x, filters[1])
    x = MaxPooling2D((2, 2))(x)

    x = _conv_block(x, filters[2])
    x = MaxPooling2D((2, 2))(x)

    x = Flatten()(x)
    x = Dense(256, activation='relu')(x)
    x = Dropout(dropout_rate)(x)
    out = Dense(num_classes, activation='softmax')(x)

    return Model(inputs=inp, outputs=out)

#### 🚂 **4. Model Eğitimi ve Kaydetme**


In [ ]:
if __name__ == '__main__':
    kok_dizin = os.path.join(os.getcwd(), "Project2")
    yollar, etiketler = mammo_gorunumlerini_listele(kok_dizin)
    X, y = convert_to_dataset(yollar, etiketler,target_size=target_size)
    X_egitim_val, X_test, y_egitim_val, y_test = train_test_split(X, y, test_size=0.1, stratify=y, random_state=42)
    np.save("X_test_2_1.npy", X_test)
    np.save("y_test_2_1.npy", y_test)
    model = create_cnn_model()
    model.compile(optimizer=Adam(learning_rate=learning_rate),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

    geri_cagirmalar = [
        EarlyStopping(patience=earlystop_patience, restore_best_weights=True),
        ReduceLROnPlateau(patience=reduce_lr_patience, factor=0.5)
    ]
    #chatgpt
    model.fit(X_egitim_val, pd.get_dummies(y_egitim_val),
          epochs=epochs, batch_size=batch_size,validation_split=0.1,
          callbacks=geri_cagirmalar, verbose=1)

    olasiliklar = model.predict(X_test)
    esikler = np.linspace(0.4, 0.6, 21)
    en_iyi_f1, en_iyi_T_m, en_iyi_T_b = 0, 0.47, 0.53
    for T_m_aday in esikler:
        for T_b_aday in esikler:
            tahminler = [2 if p[2] >= T_m_aday else 1 if p[1] >= T_b_aday else 0 for p in olasiliklar]
            f1 = f1_score(y_test, tahminler, average='macro')
            if f1 > en_iyi_f1:
                en_iyi_f1, en_iyi_T_m, en_iyi_T_b = f1, T_m_aday, T_b_aday

Epoch 1/50
61/61 [==============================] - 15s 163ms/step - loss: 2.0292 - accuracy: 0.7960 - val_loss: 1.0639 - val_accuracy: 0.1495
Epoch 2/50
61/61 [==============================] - 8s 137ms/step - loss: 0.4347 - accuracy: 0.8339 - val_loss: 0.9472 - val_accuracy: 0.7944
Epoch 3/50
61/61 [==============================] - 8s 137ms/step - loss: 0.3681 - accuracy: 0.8598 - val_loss: 0.9385 - val_accuracy: 0.7944
Epoch 4/50
61/61 [==============================] - 8s 136ms/step - loss: 0.3110 - accuracy: 0.8785 - val_loss: 1.0144 - val_accuracy: 0.7944
Epoch 5/50
61/61 [==============================] - 8s 137ms/step - loss: 0.2803 - accuracy: 0.8879 - val_loss: 0.8434 - val_accuracy: 0.7944
Epoch 6/50
61/61 [==============================] - 8s 137ms/step - loss: 0.2969 - accuracy: 0.8853 - val_loss: 0.8925 - val_accuracy: 0.7944
Epoch 7/50
61/61 [==============================] - 8s 137ms/step - loss: 0.2755 - accuracy: 0.8951 - val_loss: 0.9012 - val_accuracy: 0.3551
Epoch

 Metirkler**

In [ ]:
nihai_tahminler = [2 if p[2] >= en_iyi_T_m else 1 if p[1] >= en_iyi_T_b else 0 for p in olasiliklar]
print(f"En iyi eşik sınırı: T_m={en_iyi_T_m:.2f}, T_b={en_iyi_T_b:.2f}")
print(classification_report(y_test, nihai_tahminler, target_names=['normal','benign','cancer']))
print(confusion_matrix(y_test, nihai_tahminler))
print("Doğruluk:", accuracy_score(y_test, nihai_tahminler))
print("Precision:", precision_score(y_test, nihai_tahminler, average='macro'))
print("Recall:", recall_score(y_test, nihai_tahminler, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), olasiliklar, average='macro', multi_class='ovr'))
except:
    print("AUC hesaplanamadı (muhtemelen tek sınıf tahmini nedeniyle)")
with open("optimized_thresholds.txt", "w") as f:
    f.write(f"Best T_m: {en_iyi_T_m}\nBest T_b: {en_iyi_T_b}\nBest F1: {en_iyi_f1}")

En iyi eşik sınırı: T_m=0.40, T_b=0.40
              precision    recall  f1-score   support

      normal       0.98      0.97      0.97       187
      benign       0.71      0.92      0.80        39
      cancer       1.00      0.17      0.29        12

    accuracy                           0.92       238
   macro avg       0.89      0.69      0.69       238
weighted avg       0.93      0.92      0.91       238

[[181   6   0]
 [  3  36   0]
 [  1   9   2]]
Doğruluk: 0.9201680672268907
Kesinlik: 0.8947535771065183
Duyarlılık: 0.6858860094154212
AUC: 0.9487354324349341


In [8]:
#### 💾 **6. Model ve Eşik Kayıtları**


In [9]:
model_name = "model1_2.h5"
model.save(model_name)
print(f"Model kaydedildi: {model_name}")

Model kaydedildi: model1_2.h5
