In [1]:
import os
import re
import cv2
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score, precision_score, recall_score, roc_auc_score
from tensorflow.keras.models import load_model
import joblib
import xgboost as xgb


**#### 🧠 **MLP****

In [2]:
model = load_model("MLP_2_2.h5")
T_m = 0.24
T_b = 0.25
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}


In [3]:


X_test = np.load("X_test_2_2.npy")
y_test = np.load("y_test_2_2.npy")

In [4]:
probs = model.predict(X_test)
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]

 Metirkler**

In [5]:
print("\n --------------MLP RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------MLP RESULTS----------------
              precision    recall  f1-score   support

      normal       0.84      0.70      0.76       187
      benign       0.27      0.56      0.37        39
      cancer       0.00      0.00      0.00        12

    accuracy                           0.64       238
   macro avg       0.37      0.42      0.38       238
weighted avg       0.71      0.64      0.66       238

Confusion Matrix:
 [[130  54   3]
 [ 17  22   0]
 [  7   5   0]]
Accuracy: 0.6386554621848739
Precision: 0.37192026080914964
Recall: 0.419763243292655
📌 F1 Score: 0.376376669925057
AUC: 0.5956850574218887


**#### 🧠 **RANDOM FOREST****

In [6]:
model = joblib.load("RF_2_2.pkl")
T_m = 0.23
T_b = 0.36
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}

In [7]:
X_test = np.load("X_test_2_2.npy")
y_test = np.load("y_test_2_2.npy")
probs = model.predict_proba(X_test) 
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]
print("\n --------------RF RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------RF RESULTS----------------
              precision    recall  f1-score   support

      normal       0.81      0.84      0.83       187
      benign       0.32      0.26      0.29        39
      cancer       0.15      0.17      0.16        12

    accuracy                           0.71       238
   macro avg       0.43      0.42      0.43       238
weighted avg       0.70      0.71      0.71       238

Confusion Matrix:
 [[158  20   9]
 [ 27  10   2]
 [  9   1   2]]
Accuracy: 0.7142857142857143
Precision: 0.43028659623272186
Recall: 0.4226655697243933
📌 F1 Score: 0.4250368703912011
AUC: 0.6235867676520411


**#### 🧠 **XP-Boost****

In [8]:
loaded_xgb_model_booster = xgb.Booster() # Initialize an empty booster
loaded_xgb_model_booster.load_model("XGBoost_2_2.json") # Load the model into the booster object
# No need for 'model =' here, loaded_xgb_model_booster now holds the model
T_m = 0.31
T_b = 0.27
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}

X_test = np.load("X_test_2_2.npy")
y_test = np.load("y_test_2_2.npy")

dtest_predict = xgb.DMatrix(X_test) 
probs = loaded_xgb_model_booster.predict(dtest_predict) 
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]



In [9]:

print("\n --------------XP-B RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------XP-B RESULTS----------------
              precision    recall  f1-score   support

      normal       0.81      0.82      0.81       187
      benign       0.27      0.33      0.30        39
      cancer       1.00      0.08      0.15        12

    accuracy                           0.70       238
   macro avg       0.69      0.41      0.42       238
weighted avg       0.73      0.70      0.70       238

Confusion Matrix:
 [[153  34   0]
 [ 26  13   0]
 [ 10   1   1]]
Accuracy: 0.7016806722689075
Precision: 0.6934523809523809
Recall: 0.4116161616161616
📌 F1 Score: 0.42217550526427994
AUC: 0.5859079905624176
