In [1]:
import os
import re
import cv2
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score, precision_score, recall_score, roc_auc_score
from tensorflow.keras.models import load_model
import joblib
import xgboost as xgb


**#### 🧠 **MLP****

In [2]:
model = load_model("MLP_1_22.h5")
T_m = 0.20
T_b = 0.20
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}


In [3]:


X_test = np.load("X_test_1_2.npy")
y_test = np.load("y_test_1_2.npy")

In [4]:
probs = model.predict(X_test)
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]

 Metirkler**

In [5]:
print("\n --------------MLP RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------MLP RESULTS----------------
              precision    recall  f1-score   support

      normal       0.43      0.50      0.46       241
      benign       0.39      0.67      0.49       268
      cancer       0.33      0.05      0.09       272

    accuracy                           0.40       781
   macro avg       0.38      0.41      0.35       781
weighted avg       0.38      0.40      0.34       781

Confusion Matrix:
 [[121 106  14]
 [ 75 179  14]
 [ 86 172  14]]
Accuracy: 0.4020486555697823
Precision: 0.38469874968315304
Recall: 0.4071519082643895
📌 F1 Score: 0.34856006104436427
AUC: 0.567929665661704


**#### 🧠 **RANDOM FOREST****

In [6]:
model = joblib.load("RF_1_2.pkl")
T_m = 0.43
T_b = 0.40
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}

In [7]:
X_test = np.load("X_test_1_2.npy")
y_test = np.load("y_test_1_2.npy")
probs = model.predict_proba(X_test) 
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]
print("\n --------------RF RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------RF RESULTS----------------
              precision    recall  f1-score   support

      normal       0.35      0.41      0.38       241
      benign       0.39      0.37      0.38       268
      cancer       0.33      0.31      0.32       272

    accuracy                           0.36       781
   macro avg       0.36      0.36      0.36       781
weighted avg       0.36      0.36      0.36       781

Confusion Matrix:
 [[98 63 80]
 [84 99 85]
 [96 93 83]]
Accuracy: 0.3585147247119078
Precision: 0.3584768996946655
Recall: 0.36039634934917797
📌 F1 Score: 0.3584883936330128
AUC: 0.5218896962093184


**#### 🧠 **XP-Boost****

In [8]:
loaded_xgb_model_booster = xgb.Booster() # Initialize an empty booster
loaded_xgb_model_booster.load_model("XGBoost_1_2.json") # Load the model into the booster object
# No need for 'model =' here, loaded_xgb_model_booster now holds the model
T_m = 0.40
T_b = 0.40
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}

X_test = np.load("X_test_1_2.npy")
y_test = np.load("y_test_1_2.npy")

dtest_predict = xgb.DMatrix(X_test) 
probs = loaded_xgb_model_booster.predict(dtest_predict) 
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]
T_m = 0.40
T_b = 0.40


In [9]:

print("\n --------------XP-B RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------XP-B RESULTS----------------
              precision    recall  f1-score   support

      normal       0.35      0.63      0.45       241
      benign       0.42      0.26      0.32       268
      cancer       0.40      0.27      0.33       272

    accuracy                           0.38       781
   macro avg       0.39      0.39      0.37       781
weighted avg       0.39      0.38      0.36       781

Confusion Matrix:
 [[151  40  50]
 [138  71  59]
 [139  59  74]]
Accuracy: 0.37900128040973113
Precision: 0.39160746061358
Recall: 0.38784673775375017
📌 F1 Score: 0.3669652228040335
AUC: 0.5748431109971065
