In [19]:
import os
import re
import cv2
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score, precision_score, recall_score, roc_auc_score
from tensorflow.keras.models import load_model
import joblib
import xgboost as xgb


**#### 🧠 **MLP****

In [20]:
model = load_model("MLP_1_1.h5")
T_m = 0.40
T_b = 0.40
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}


In [21]:


X_test = np.load("X_test_1_1.npy")
y_test = np.load("y_test_1_1.npy")

In [22]:
probs = model.predict(X_test)
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]

 Metirkler**

In [23]:
print("\n --------------MLP RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------MLP RESULTS----------------
              precision    recall  f1-score   support

      normal       0.31      1.00      0.47       241
      benign       0.00      0.00      0.00       268
      cancer       0.00      0.00      0.00       272

    accuracy                           0.31       781
   macro avg       0.10      0.33      0.16       781
weighted avg       0.10      0.31      0.15       781

Confusion Matrix:
 [[241   0   0]
 [268   0   0]
 [272   0   0]]
Accuracy: 0.3085787451984635
Precision: 0.10285958173282117
Recall: 0.3333333333333333
📌 F1 Score: 0.15720808871493802
AUC: 0.5007973176121975


c:\Users\Dr.Ahmet\anaconda3\envs\tf-gpu-211\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Dr.Ahmet\anaconda3\envs\tf-gpu-211\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Dr.Ahmet\anaconda3\envs\tf-gpu-211\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

**#### 🧠 **RANDOM FOREST****

In [24]:
model = joblib.load("RF_1_1.pkl")
T_m = 0.40
T_b = 0.40
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}

In [25]:
X_test = np.load("X_test_1_1.npy")
y_test = np.load("y_test_1_1.npy")
probs = model.predict_proba(X_test) 
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]
print("\n --------------RF RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------RF RESULTS----------------
              precision    recall  f1-score   support

      normal       0.35      0.38      0.36       241
      benign       0.35      0.34      0.35       268
      cancer       0.34      0.32      0.33       272

    accuracy                           0.34       781
   macro avg       0.34      0.35      0.34       781
weighted avg       0.34      0.34      0.34       781

Confusion Matrix:
 [[91 79 71]
 [79 92 97]
 [92 94 86]]
Accuracy: 0.3444302176696543
Precision: 0.34436024425363937
Recall: 0.3456844712245461
📌 F1 Score: 0.3446803278044892
AUC: 0.5110047125108091


**#### 🧠 **XP-Boost****

In [26]:
loaded_xgb_model_booster = xgb.Booster() # Initialize an empty booster
loaded_xgb_model_booster.load_model("XGBoost_1_1.json") # Load the model into the booster object
# No need for 'model =' here, loaded_xgb_model_booster now holds the model
T_m = 0.40
T_b = 0.40
classes = ['normal', 'benign', 'cancer']
label_map = {'normal': 0, 'benign': 1, 'cancer': 2}

X_test = np.load("X_test_1_1.npy")
y_test = np.load("y_test_1_1.npy")

dtest_predict = xgb.DMatrix(X_test) 
probs = loaded_xgb_model_booster.predict(dtest_predict) 
preds = [2 if p[2] >= T_m else 1 if p[1] >= T_b else 0 for p in probs]
T_m = 0.40
T_b = 0.40


In [27]:

print("\n --------------XP-B RESULTS----------------")
print(classification_report(y_test, preds, target_names=classes))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds, average='macro'))
print("Recall:", recall_score(y_test, preds, average='macro'))
print("📌 F1 Score:", f1_score(y_test, preds, average='macro'))
try:
    print("AUC:", roc_auc_score(pd.get_dummies(y_test), probs,
                                 multi_class='ovr', average='macro'))
except:
    print("AUC hesaplanamadı.")


 --------------XP-B RESULTS----------------
              precision    recall  f1-score   support

      normal       0.36      0.56      0.44       241
      benign       0.39      0.29      0.33       268
      cancer       0.40      0.31      0.35       272

    accuracy                           0.38       781
   macro avg       0.38      0.39      0.37       781
weighted avg       0.39      0.38      0.37       781

Confusion Matrix:
 [[136  52  53]
 [119  78  71]
 [119  70  83]]
Accuracy: 0.38028169014084506
Precision: 0.38486751573708095
Recall: 0.38683572921334264
📌 F1 Score: 0.37405502656279177
AUC: 0.567432513124133
